# Generated by Django 4.2.3 on 2023-07-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveSmallIntegerField(choices=[[1, 'Low'], [2, 'Medium'], [3, 'High']], default=1)),
                ('status', models.BooleanField(choices=[[True, 'Done'], [False, 'Not Done']], default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
