# Generated by Django 4.2.3 on 2023-07-07 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'ordering': ('deadline', 'priority'), 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
